phraseapp:
  access_token: 8f2bc5ff5146811b6c737542f05fcab60f3feb60fce918c2d0199e8fe2744375
  project_id: b801c7449dd0fbff52b08e3f47793aa9
  push:
    sources:
    - file: ./app/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
  pull:
    targets:
    - file: ./app/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
